


ubuntu@ip-172-31-35-62:~/aptos-core/ecosystem/python/sdk$ poetry run python -m examples.multisig
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/aptos-core/ecosystem/python/sdk/examples/multisig.py", line 8, in <module>
    from aptos_sdk.account import Account, RotationProofChallenge
  File "/home/ubuntu/aptos-core/ecosystem/python/sdk/aptos_sdk/account.py", line 10, in <module>
    from . import asymmetric_crypto, ed25519
  File "/home/ubuntu/aptos-core/ecosystem/python/sdk/aptos_sdk/asymmetric_crypto.py", line 6, in <module>
    from typing_extensions import Protocol
ModuleNotFoundError: No module named 'typing_extensions'
ubuntu@ip-172-31-35-62:~/aptos-core/ecosystem/python/sdk$ pip install typing_extensions
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: typing_extensions in /home/ubuntu/.local/lib/python3.10/site-packages (4.8.0)
ubuntu@ip-172-31-35-62:~/aptos-core/ecosystem/python/sdk$





ubuntu@ip-172-31-35-62:~/aptos-core/ecosystem/python/sdk$ pip install typing_extensions
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: typing_extensions in /home/ubuntu/.local/lib/python3.10/site-packages (4.8.0)
ubuntu@ip-172-31-35-62:~/aptos-core/ecosystem/python/sdk$ pip3 install typing_extensions
Defaulting to user installation because normal site-packages is not writeable




ubuntu@ip-172-31-35-62:~/aptos-core/ecosystem/python/sdk$ poetry env use python3
Using virtualenv: /home/ubuntu/.cache/pypoetry/virtualenvs/aptos-sdk-Dxkupkfg-py3.10
ubuntu@ip-172-31-35-62:~/aptos-core/ecosystem/python/sdk$ poetry run python3 -m examples.multisig
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/aptos-core/ecosystem/python/sdk/examples/multisig.py", line 8, in <module>
    from aptos_sdk.account import Account, RotationProofChallenge
  File "/home/ubuntu/aptos-core/ecosystem/python/sdk/aptos_sdk/account.py", line 10, in <module>
    from . import asymmetric_crypto, ed25519
  File "/home/ubuntu/aptos-core/ecosystem/python/sdk/aptos_sdk/asymmetric_crypto.py", line 6, in <module>
    from typing_extensions import Protocol
ModuleNotFoundError: No module named 'typing_extensions'
ubuntu@ip-172-31-35-62:~/aptos-core/ecosystem/python/sdk$ poetry env list
aptos-sdk-Dxkupkfg-py3.10 (Activated)
ubuntu@ip-172-31-35-62:~/aptos-core/ecosystem/python/sdk$ poetry add typing_extensions -D
Using version ^4.8.0 for typing-extensions


  RuntimeError

  The lock file is not compatible with the current version of Poetry.
  Upgrade Poetry to be able to read the lock file or, alternatively, regenerate the lock file with the `poetry lock` command.

  at /usr/lib/python3/dist-packages/poetry/packages/locker.py:481 in _get_lock_data
      477│                 "Upgrade Poetry to ensure the lock file is read properly or, alternatively, "
      478│                 "regenerate the lock file with the `poetry lock` command."
      479│             )
      480│         elif not lock_version_allowed:
    → 481│             raise RuntimeError(
      482│                 "The lock file is not compatible with the current version of Poetry.\n"
      483│                 "Upgrade Poetry to be able to read the lock file or, alternatively, "
      484│                 "regenerate the lock file with the `poetry lock` command."
      485│             )
ubuntu@ip-172-31-35-62:~/aptos-core/ecosystem/python/sdk$ poetry lock

  RuntimeError

  The lock file is not compatible with the current version of Poetry.
  Upgrade Poetry to be able to read the lock file or, alternatively, regenerate the lock file with the `poetry lock` command.

  at /usr/lib/python3/dist-packages/poetry/packages/locker.py:481 in _get_lock_data
      477│                 "Upgrade Poetry to ensure the lock file is read properly or, alternatively, "
      478│                 "regenerate the lock file with the `poetry lock` command."
      479│             )
      480│         elif not lock_version_allowed:
    → 481│             raise RuntimeError(
      482│                 "The lock file is not compatible with the current version of Poetry.\n"
      483│                 "Upgrade Poetry to be able to read the lock file or, alternatively, "
      484│                 "regenerate the lock file with the `poetry lock` command."
      485│             )
ubuntu@ip-172-31-35-62:~/aptos-core/ecosystem/python/sdk$

https://realpython.com/dependency-management-python-poetry/#python-poetry-installation












Requirement already satisfied: typing_extensions in /home/ubuntu/.local/lib/python3.10/site-packages (4.8.0)

